### ISSUE TITLE
Why many dependenices not included in the meta packages?

### ISSUE THREAD

**Issue by Kelvin-Ng** [steup/Gentoo-ROS-Overlay#3]
rosinstall_generator is needed to install ros, but it is not included in ros-indigo-ros-base, but I think it is still reasonable as it can be removed after ros is installed.

However, to use ros, urdfdom, urdfdom_headers and console-bridge (perhaps even more) are needed. Why these packages are not pulled in by the meta package? Are there any reasons behind?

**Comment by steup** [comment]
This is completely true and needs to be fixed.

**Comment by Kelvin-Ng** [comment]
I would like to help fix the issue, but I do not know which dependencies should be included in ros-indigo-ros-base, and which should be included in ros-indigo-desktop.

**Comment by steup** [comment]
Fixed the missing dependancies with last commit
